name: CI
on: [push]
jobs:
  build:
    strategy:
      matrix:
        platform: [windows, macOS, ubuntu]
    runs-on: '${{ matrix.platform }}-latest'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          pip install conan cmake
          conan install . -s build_type=Debug --install-folder=debug --build=missing
      - name: Build Project
        run: |
          cmake . -B debug
          cmake --build debug --target aquarium
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.platform }}
          path: debug/bin
