name: CI
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [windows, macOS, ubuntu]
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - name: Set up python
        uses: actions/setup-python@v1
      - name: Check out source
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install conan cmake
          conan install . -s build_type=Debug --install-folder=debug --build=missing
      - name: Package
        run: |
          cmake . -B debug
          cmake --build debug --target package
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: debug/packages
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            debug/packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
