name: CI
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [windows, macOS, ubuntu]
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - name: Set up python
        uses: actions/setup-python@v1
      - name: Check out source
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip install conan cmake
          conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
          conan install . -s build_type=Release --install-folder=release --build=missing
      - name: Package
        run: |
          cmake -B release
          cmake --build release --target package --config Release
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.platform }}
          path: release/packages
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
